use  supermarket_sales;
select * from sales; 
desc sales;
set sql_safe_updates =0;
update sales set date=str_to_date(date,"%m/%d/%Y");


-- Does the membership depend on customer rating ?

select count(customer_type) as Member_customers from sales where customer_type="Member" and rating>7; 
select count(customer_type)  as Nonmember_customers from sales where customer_type="Normal" and rating >7;

/* Out of total 1000 customers in all 3 branches the customers who rated more than 7 with memebership 238 customers and 
without membership 243 customers.*/

select count(customer_type) as member_customers,customer_type,rating from sales 
group by rating ,customer_type
 order by rating desc ;
 
/* And from this we can observe there is'nt much significant difference in the customer ratings w.r.t customers count with membership/without membership
So this indicates that ratings are independent on membership of customers.*/




-- Which product category generates the highest income?

select floor(sum(total)) as net_income ,product_line from sales group by product_line order by net_income desc ;
-- Food and beverages generates the highest income of 56144 and Health and beauty generates the lowest of 49193 from all the 3 branches sales.



-- Are there any differences in indicators between men and women?

select floor(sum(total)) as net_income ,gender from sales group by gender order by net_income desc ;
select floor(sum(total)) as net_income ,gender,product_line from sales group by gender,product_line order by net_income desc ;
select floor(sum(total)) as net_income ,branch,gender from sales group by branch,gender order by net_income desc ;

/* overall amount generated by female customers is comapritively more than male customers but with not munch difference (around 13000),
  In which the female customers spent more amount on Food and beverages where as male customers spent more on Health and Beauty in terms of product category.
  Whereas in terms of supermarket branches, the highest amount is generated in branch C and then in A by female customers and 
  the least amount generated in all branches is by male customers in branch C .
  We can conclude that the gender can be considered as a factor of sales.*/
  
  
  
  -- Which is the most used payment method?
  
  select count(payment) as payment_count ,payment from sales group by payment order by payment_count desc;
  
  -- Considering overall transactions both Ewallet and Cash are the most common mode of payment .
  
  
  
  -- Which city captures maximum sales?
  
  select city, floor(sum(total)) as sales_income,branch from sales group by city,branch order by sales_income desc;
  
  -- Naypyitaw (Branch C) generated highest sales with income 110568 and Mandalay has minimum sales.
  

  
  -- Which month has generated more income ?
  
select floor(sum(total)) as month_wise_sales,monthname(date) as "Month name" from sales
   group by monthname(date) order by month_wise_sales desc;
  
 
  -- The maximum sales are generated in the month of January followed by March and the least in Febuary.
  
  
  
  -- At which hours in a day the store is busy?
  
  select floor(sum(total)) as total_sales,
  case when time>="10:00" and time<="12:00" then "Pre lunch hours"
  when time>="12:00" and time<="14:00" then "lunch hours"
  when time>="14:00" and time<="16:00" then "Post lunch hours"
  when time>="16:00" and time<="19:00" then "Evening hours"
   when time>="19:00" and time<="21:00" then "Dinner hours"
   else"Extra hours"
  end as hourly_info
  from sales group by hourly_info order by total_sales desc;
  
/* The sales are peak at evening hours i.e around 4-7pm followed by dinner hours and minimum at lunch hours i.e 12-2pm
    which indicates that the supermarket is busiest in the evening hours. */

   
-- What is the percent of sales that is carried on credit card for purchasing fashion accessories to the total sales?

select (saleson_creditcard/total_sales)*100 as " sales on credit card" from 
(select floor(sum(total)) as saleson_creditcard from sales 
where product_line="Fashion accessories" and payment="Credit card" ) as a,  
(select floor(sum(total)) as total_sales from sales ) as b ;

-- 5.36 % of income has generated from Fashion accessories through credit card with respective to the total sales carried out .


--  Which Category generates more gross income ?

select  product_line,floor(sum(gross_income)) as total_grossincome from sales 
group by product_line  order by total_grossincome desc;

/*The gross income generated is highest in category Food and beverages followed by Sports and travel ,
 effective marketing strategies can enhance the sales in Health and beauty.*/


-- What are the dependents of COGS?

select floor(sum(cogs)) as total_cogs,sum(total) as net_income,count(quantity) as total_items_sold,product_line from sales
 group by product_line order by total_cogs desc ;

/* Food and beverages generated more income with more number of items sold but the cost of goods sold is also highest which might
 result in minimum amounts of profit; 
 where as Health and beauty sales are least and the cost of goods sold is also minimum 
this indicates the profit attained by health and beauty is similar to the profits attained by food and beverages.*/




-- Which Days have sales below average day sales?


select * from
(select dayname(date) as "Day name",floor(avg(total)) as daywise_avg_sales from sales group by dayname(date)) as a,
(select floor(avg(total)) as total_avg_sales from sales ) as b
where total_avg_sales>daywise_avg_sales ;

/*We can observe that Monday had sales lower than average of sales 
which indicates that an effort can be made to maximise the sales by additional offers .*/